version: '2'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    networks:
      - net1
  backend:
    build: backend/.
    ports: 
      - "8082:8080"
    networks:
      - net1
    depends_on:
      - db
  frontend:
    build: frontend/.
    ports: 
      - "80:80"
    networks:
      - net1
    depends_on: 
      - backend

networks:
  net1:
